defaults:
    language: 'en'

#settings:
#    root:
#        context: '..'

# Example of functionality I want in Hector, don't really need this
# globals = like a route, but doesn't generate pages and is instead
# available as context to any route. Also, as it is for routes, 
# context is optional. Either because you don't need it or because
# your plugin actually acts as a generator (making Hector much more
# flexible in what kind of data it'll ingest)
globals:
    persons:
        context: 'bios/{name}'
        pipes:
            - make-things-pluggable.js
    # metadata fields to grab (so we have all unique values)
    # useful e.g. for dynamic menus or for feeds
    facets:
        context: '{layout}/{year}-{month}-{day}-{permalink}'
        pipes:
            - get-unique-values.js
        output: 
            - render

routes:
    assets:
        route: 'assets'
        context: 'assets'
        pipes:
            - list-files
        output:
            - copy-assets
    posts:
        route: '{year}/{month}/{day}/{permalink}/'
        layout: '{layout}'
        context: 'posts/{year}-{month}-{day}-{permalink}'
        # if `canonical` is specified, then we'll log this context somewhere
        # and whenever we use it again, we'll add the canonical URL to the
        # Hector metadata. (Useful for feeds etc.)
        canonical: yes
        defaults:
            layout: 'blogpost'
    pages:
        route: '{permalink}/'
        layout: '{layout}'
        context: 'pages/{permalink}'
        defaults:
            layout: 'page'
    feed:
        route: 'feed.atom'
        layout: 'feed'
        context: 'posts/{year}-{month}-{day}-{permalink}'
        defaults:
            title: 'The feed for example.org'